# Generated by Django 4.0.5 on 2022-07-14 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='static/product/img')),
                ('product_description', models.TextField()),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='상품 등록일')),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='product_category', to='product.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_option_detail', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_amount', models.IntegerField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='product.product')),
            ],
        ),
    ]
