# Generated by Django 4.0.5 on 2022-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedlist',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
