# Generated by Django 4.0.5 on 2022-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='사용자 계정')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일 주소')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('profile_img', models.ImageField(blank=True, upload_to='static/user/profile_img')),
                ('user_type', models.CharField(max_length=10, verbose_name='회원 유형')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
